services:

  # =========================
  # AUTH BACKEND
  # =========================

  backend1:
    build: ./backend1
    restart: unless-stopped
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: blog_db
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3301:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - proyecto_net

  # =========================
  # BLOG BACKEND 1
  # =========================

  backend2:
    build: ./backend2
    restart: unless-stopped
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: blog_db
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - proyecto_net

  # =========================
  # BLOG BACKEND 2
  # =========================

  backend3:
    build: ./backend3
    restart: unless-stopped
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: blog_db
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - proyecto_net

  # =========================
  # BACKEND LOAD BALANCER
  # =========================

  backend-balancer:
    build: ./backend-balancer
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - proyecto_net

  # =========================
  # FRONTEND INSTANCE 1
  # =========================

  frontend1:
    build:
      context: ./frontend1
      args:
        VITE_AUTH_API_URL: http://192.168.50.3:8080/api
        VITE_BLOG_API_URL: http://192.168.50.3:8080/api
    restart: unless-stopped
    networks:
      - proyecto_net

  # =========================
  # FRONTEND INSTANCE 2
  # =========================

  frontend2:
    build:
      context: ./frontend2
      args:
        VITE_AUTH_API_URL: http://192.168.50.3:8080/api
        VITE_BLOG_API_URL: http://192.168.50.3:8080/api
    restart: unless-stopped
    networks:
      - proyecto_net

  # =========================
  # FRONTEND LOAD BALANCER
  # =========================

  frontend-balancer:
    build: ./frontend-balancer
    restart: unless-stopped
    ports:
      - "8090:80"
    depends_on:
      - frontend1
      - frontend2
    networks:
      - proyecto_net
  # =========================
  # DATABASE
  # =========================

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - proyecto_net

# =========================
# NETWORK
# =========================

networks:
  proyecto_net:
    driver: bridge
