version: "3.8"

services:
  balancer:
    build: ./balancer
    ports:
      - "5080:80"
    depends_on:
      - web1
      - web2
      - web3

  web1:
    build: ./web
    volumes:
      - ./web/html1:/var/www/html/

  web2:
    build: ./web
    volumes:
      - ./web/html2:/var/www/html/

  web3:
    build: ./web
    volumes:
      - ./web/html3:/var/www/html/

  artillery:
    build: ./artillery
    volumes:
      - ./artillery/reports:/app/reports # Para sacar los reportes al host
    depends_on:
      - balancer
    # Esta línea permite que artillery se lance solo bajo demanda
    profiles:
      - tools
