#Modulo que mejora el procesameinto
LoadModule mpm_event_module modules/mod_mpm_event.so
#Permite la memoria compartida
LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
#Permite reenviar solicitudes
LoadModule proxy_module modules/mod_proxy.so
#Permite realizar el balanceo de carga
LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
#Permite reenviar peticiones HTTP a los backends
LoadModule proxy_http_module modules/mod_proxy_http.so

# Algoritmo 1: Round Robin
LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so

# Algoritmo 2: Least Connections
LoadModule lbmethod_bybusyness_module modules/mod_lbmethod_bybusyness.so


#AUTH CLUSTER
<Proxy "balancer://auth_cluster">
    BalancerMember http://auth1:3000
    BalancerMember http://auth2:3000

    ProxySet lbmethod=byrequests
</Proxy>

#ADMIN CLUSTER
<Proxy "balancer://admin_cluster">
    BalancerMember http://admin1:3000
    BalancerMember http://admin2:3000

    ProxySet lbmethod=byrequests
</Proxy>

#POSTS CLUSTER
<Proxy "balancer://posts_cluster">
    BalancerMember http://posts1:3000
    BalancerMember http://posts2:3000

    ProxySet lbmethod=bybusyness
</Proxy>

#AUTH ROUTING
ProxyPass "/api/auth" "balancer://auth_cluster"
ProxyPassReverse "/api/auth" "balancer://auth_cluster"

#ADMIN ROUTING
ProxyPass "/api/admin" "balancer://admin_cluster"
ProxyPassReverse "/api/admin" "balancer://admin_cluster"

#POSTS ROUTING
ProxyPass "/api/posts" "balancer://posts_cluster"
ProxyPassReverse "/api/posts" "balancer://posts_cluster"
