# =========================
# CORS HEADERS (must be first)
# =========================

Header always set Access-Control-Allow-Origin "http://192.168.50.3:8090"
Header always set Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
Header always set Access-Control-Allow-Headers "Authorization, Content-Type"
Header always set Access-Control-Max-Age "1728000"

# Handle OPTIONS preflight — return 204 immediately, don't proxy it
RewriteEngine On
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ $1 [R=204,L]


# Algoritmo 1: Round Robin
LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so

# Algoritmo 2: Least Connections
LoadModule lbmethod_bybusyness_module modules/mod_lbmethod_bybusyness.so


# =========================
# BLOG CLUSTER
# =========================

<Proxy "balancer://blog_cluster">
    BalancerMember http://backend2:3000
    BalancerMember http://backend3:3000

#Descomentar para usar Least Connections
    ProxySet lbmethod=bybusyness

#Descomentar para usar Least Round Robin
#    ProxySet lbmethod=byrequests
</Proxy>

# =========================
# AUTH ROUTING
# =========================

ProxyPass "/api/auth/" "http://backend1:3000/api/auth/"
ProxyPassReverse "/api/auth/" "http://backend1:3000/api/auth/"

# =========================
# BLOG ROUTING
# =========================

ProxyPass "/api/blog" "balancer://blog_cluster/api/blog/"
ProxyPassReverse "/api/blog" "balancer://blog_cluster/api/blog/"

# =========================
# BALANCER MANAGER
# =========================

<Location "/balancer-manager">
    SetHandler balancer-manager
    Require all granted
</Location>
